In [1]:
from sklearn.datasets import load_iris #load the iris data as a dictionary-like object(Bunch)
iris_dataset = load_iris()

In [5]:
print("Keys of iris_dataset: \n{}".format(iris_dataset.keys())) #prints the keys

Keys of iris_dataset: 
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [7]:
print(iris_dataset['DESCR'][:193] + "\n...") #DESCR is the key that describes the dataset

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive 
...


In [8]:
print("Target names: {}".format(iris_dataset['target_names'])) #types of species

Target names: ['setosa' 'versicolor' 'virginica']


In [9]:
print("Feature names: \n{}".format(iris_dataset['feature_names'])) #features of the flower

Feature names: 
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [10]:
print("Type of data: {}".format(type(iris_dataset['data']))) #numeric data is an array in numpy, rows are flowers and columns are 4 measurements

Type of data: <class 'numpy.ndarray'>


In [11]:
print("Shape of data: {}".format(iris_dataset['data'].shape))

Shape of data: (150, 4)


In [13]:
print("First five columns of data:\n{}".format(iris_dataset['data'][:5])) #data of first 5 samples

First five columns of data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [15]:
print("Type of target: {}".format(type(iris_dataset['target']))) #target array is also a numpy array

Type of target: <class 'numpy.ndarray'>


In [17]:
print("Shape of target: {}".format(iris_dataset['target'].shape)) #1D array

Shape of target: (150,)


In [18]:
print("Target:\n{}".format(iris_dataset['target'])) #species is encoded from 0 to 2 since 3 types of species

Target:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
